### ISSUE TITLE
Error During Dockerfile Build Process

### ISSUE THREAD

**Issue by pierecnlnd** [waiwera/waiwera#18]
I need to inform you for an issue encountered while building the Dockerfile. The current version of Python installed for the image is Python 2, which is causing an error during the execution of "pip install ansible." The error suggests compatibility issues with the Python version and the installed Ansible version.

178.2     Complete output from command python setup.py egg_info:
178.2     Traceback (most recent call last):
178.2       File "<string>", line 1, in <module>
178.2       File "/tmp/pip-install-okX9dC/ansible/setup.py", line 14, in <module>
178.2         setup()
178.2       File "/tmp/pip-build-env-qhiGGH/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
178.2         return distutils.core.setup(**attrs)
178.2       File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
178.2         dist.parse_config_files()
178.2       File "/tmp/pip-build-env-qhiGGH/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
178.2         ignore_option_errors=ignore_option_errors)
178.2       File "/tmp/pip-build-env-qhiGGH/lib/python2.7/site-packages/setuptools/config.py", line 116, in parse_configuration
178.2         options.parse()
178.2       File "/tmp/pip-build-env-qhiGGH/lib/python2.7/site-packages/setuptools/config.py", line 426, in parse
178.2         section_parser_method(section_options)
178.2       File "/tmp/pip-build-env-qhiGGH/lib/python2.7/site-packages/setuptools/config.py", line 399, in parse_section
178.2         self[name] = value
178.2       File "/tmp/pip-build-env-qhiGGH/lib/python2.7/site-packages/setuptools/config.py", line 184, in __setitem__
178.2         value = parser(value)
178.2       File "/tmp/pip-build-env-qhiGGH/lib/python2.7/site-packages/setuptools/config.py", line 577, in _parse_packages
178.2         'find_namespace: directive is unsupported on Python < 3.3')
178.2     distutils.errors.DistutilsOptionError: find_namespace: directive is unsupported on Python < 3.3
178.2
178.2     ----------------------------------------
179.7 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-okX9dC/ansible/

In my attempt to resolve this, I switched to Python 3 for the image, but encountered an error related to the ansible-core version. To facilitate a swift resolution, could you kindly provide information on the specific Ansible version installed, especially regarding its compatibility with Python 2 or Python 3? This will greatly assist in ensuring the seamless execution of the Dockerfile.

Your prompt attention to this matter is highly appreciated.

**Comment by acroucher** [comment]
This issue has been addressed recently on the Waiwera `testing` branch (see commit ce2cd43), and the changes will be merged into the next release. As well as upgrading the Docker build to Python 3, some changes to the Ansible config were needed. The Docker image has also been upgraded from Debian 10 to 12.

**Comment by pierecnlnd** [comment]
Thank you for your prompt reply. I have encountered an issue while utilizing the testing branch version of the Dockerfile, and the error generated is as follows.

ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.

**Comment by acroucher** [comment]
I don't think you should get that error any more if you are running the latest testing branch - the Ansible `include` statements have been replaced by `include_tasks` and `import_tasks` in commit a62ab01.

You can check e.g. the file `install/ansible/roles/common/tasks/main.yml:24` in your source tree, which used to have an `include` but now has an `import_tasks`.

**Comment by pierecnlnd** [comment]
I apologize for any confusion; it was indeed my oversight. I should have initially cloned the testing branch. Thank you.
